### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by SecUpwN** [CopperheadOS/platform_packages_apps_Updater#1]
[![F-Droid](https://f-droid.org/wp-content/uploads/2014/04/cropped-header_resp1.png)](https://f-droid.org/)

Good evening @thestinger! Since you've recently told me that not all devives like my beloved HTC will be able to enjoy `CopperheadOS`, I wonder if it makes sense publishing the `CopperheadOS Updater` on [F-Droid](https://f-droid.org/) so that security enthusiasts like me can at least enjoy a few more secure apps and updates?

**Comment by thestinger** [comment]
@SecUpwN: This Updater app is the over-the-air update client for the operating system. I forked it from CyanogenMod's implementation and it likely still needs some adjustments to work properly in CopperheadOS. The server implementation is at https://github.com/copperhead/android_ota_manager.

**Comment by thestinger** [comment]
I plan on making our own F-Droid repository to do hardened builds of applications that aren't simply bundled with the OS but they wouldn't be able to run outside of CopperheadOS because they'll be calling standard C library APIs that aren't available there. Some are available in AOSP master since I upstreamed a fair bit of it but it's not the case for all of the APIs called by external code.

**Comment by SecUpwN** [comment]
Thanks for the clarifications, @thestinger. I guess you're already including our app [AIMSICD](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector) in your ROM? It is now possible to build a system APK, we'd prefer if you would uodate the system falvor when we push a new release. Possible?

**Comment by thestinger** [comment]
Need to add it back now that the OS has been ported over to AOSP, but that's the plan. It will definitely be kept up-to-date. It's no problem to update the OS every few days to push out various things.

**Comment by thestinger** [comment]
BTW, the real bug tracker is at https://github.com/copperhead/bugtracker. I just disable the ones on these repositories to make it easier to keep track. I just hadn't disabled this one yet but I will in a bit :P.
